partie Infra du ticket 123
betagouv/agora-back pull request #158
Opened 2023-06-27 14:49 UTC by imaneryane

2023-06-27 15:33 UTC, thierrylee requested changes

2023-06-27 15:33 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/domain/ConsultationUpdate.kt
> +    val videoTranscription: String?,
Ce sera peut-être plus simple dans un objet dédié, comme `Explanation`

2023-06-27 15:33 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/domain/ConsultationUpdate.kt
> +    val conclusionDescription: String?,
Idem tu peux faire un objet dédié

2023-06-27 15:33 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/consultationUpdates/repository/ConsultationUpdateRepositoryImpl.kt
> +    private fun getExplanations(consultationUpdateUUId: UUID): List<ExplanationDTO> {
A faire dans un autre Repository: il s'agit d'une autre table, la consolidation des données se fera dans un UseCase SAUF SI `Explanation` est dans l'objet domain `ConsultationUpdate`. Ce qui semble être le cas

2023-06-27 15:33 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/consultationUpdates/repository/ConsultationUpdateRepositoryImpl.kt
>          id = UUID.fromString(CONSULTATION_UPDATE_NOT_FOUND_ID),
Utiliser `UuidUtils` ?

2023-06-27 15:33 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/consultationUpdates/repository/ExplanationMapper.kt
> +            isTogglable = dto.isTogglable == IS_TOGGLABLE_FALSE_VALUE,
C'est plutôt l'inverse,`isTogglable` doit être à `true` si la valeur est à `true`, pas à `false` 🤔

2023-06-27 17:18 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/domain/ConsultationUpdate.kt
> +    val videoTranscription: String?,
done

2023-06-27 17:18 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/domain/ConsultationUpdate.kt
> +    val conclusionDescription: String?,
done

2023-06-27 17:20 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/consultationUpdates/repository/ExplanationMapper.kt
> +            isTogglable = dto.isTogglable == IS_TOGGLABLE_FALSE_VALUE,
done

2023-06-27 17:43 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/consultationUpdates/repository/ConsultationUpdateRepositoryImpl.kt
>          id = UUID.fromString(CONSULTATION_UPDATE_NOT_FOUND_ID),
done

2023-06-28 08:23 UTC, thierrylee approved these changes

2023-06-28 08:47 UTC, merged