Feat224 228/envoi notif new consultation etensuite
betagouv/agora-back pull request #178
Opened 2023-07-07 09:44 UTC by imaneryane

2023-07-07 14:27 UTC, thierrylee requested changes

2023-07-07 14:27 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/login/repository/UserRepositoryImpl.kt
> +    private fun findUserDTO(userUUID: UUID?) = getAllUserDTO().find { userDTO -> userDTO.id == userUUID }
Pourquoi l'UUID est nullable ? 🤔

2023-07-07 14:27 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NewConsultationNotificationController.kt
> +            else -> ResponseEntity.ok().body("Notification envoyée avec succès à : $successResponseNumber")
Je pense que ça peut être intéressant de savoir combien n'ont pas reçu la notif

2023-07-07 14:27 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/repository/NotificationRepositoryImpl.kt
> +            .putData("consultationId", request.consultationId)
Les magic string à mettre dans une constante ce sera plus parlant

2023-07-07 14:27 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/repository/NotificationRepositoryImpl.kt
> +            .addAllTokens(request.fcmTokenList)
A vérifier, c'est possible que y'ait une exception qui peut être levée ici

2023-07-07 14:27 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/notification/SendNewConsultationNotificationUseCase.kt
> +        type: String,
Mettre un enum pour le type ?

2023-07-07 14:34 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/login/repository/UserRepositoryImpl.kt
> +    private fun findUserDTO(userUUID: UUID?) = getAllUserDTO().find { userDTO -> userDTO.id == userUUID }
done

2023-07-07 14:47 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NewConsultationNotificationController.kt
> +            else -> ResponseEntity.ok().body("Notification envoyée avec succès à : $successResponseNumber")
done

2023-07-07 14:52 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/repository/NotificationRepositoryImpl.kt
> +            .putData("consultationId", request.consultationId)
done

2023-07-07 15:13 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/usecase/notification/SendNewConsultationNotificationUseCase.kt
> +        type: String,
done

2023-07-10 08:29 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NewConsultationNotificationController.kt
> +                    "Notification envoyée avec succès à : ${responseResult.first} utilisateurs et échec d'envoi à : ${responseResult.second} utilisateurs"
`Notification envoyée avec succès à : ${responseResult.first} / ${responseResult.second} utilisateurs` c'est suffisant

2023-07-10 08:31 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/notification/SendNewConsultationNotificationUseCase.kt
> +        type: String,
Je vois marqué "done" mais c'est toujours une String

2023-07-10 11:54 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NewConsultationNotificationController.kt
> +                    "Notification envoyée avec succès à : ${responseResult.first} utilisateurs et échec d'envoi à : ${responseResult.second} utilisateurs"
done

2023-07-10 11:54 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/usecase/notification/SendNewConsultationNotificationUseCase.kt
> +        type: String,
paramètre 'type' supprimé

2023-07-10 11:57 UTC, thierrylee approved these changes

2023-07-10 11:57 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NewConsultationNotificationController.kt
>  class NewConsultationNotificationController(
Renommer en `ConsultationNotificationController` ?

2023-07-10 11:57 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NewConsultationNotificationController.kt
> +            CONSULTATION_DETAILS_NOTIFICATION_TYPE -> sendConsultationNotificationUseCase.sendNewConsultationNotification(
Si le type ne sert que pour 1 cas, enlever le type

2023-07-10 11:57 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NewConsultationNotificationController.kt
> +        @RequestParam("type") type: String,
Idem là

2023-07-10 11:57 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/notification/repository/NotificationRepository.kt
>  data class NewConsultationNotificationRequest(
Renommer en `ConsultationNotificationRequest` ?

2023-07-10 12:26 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NewConsultationNotificationController.kt
>  class NewConsultationNotificationController(
done

2023-07-10 12:26 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/usecase/notification/repository/NotificationRepository.kt
>  data class NewConsultationNotificationRequest(
done

2023-07-10 12:34 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NewConsultationNotificationController.kt
> +            CONSULTATION_DETAILS_NOTIFICATION_TYPE -> sendConsultationNotificationUseCase.sendNewConsultationNotification(
done

2023-07-10 12:34 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NewConsultationNotificationController.kt
> +        @RequestParam("type") type: String,
done

2023-07-10 12:38 UTC, merged