Feat/3 recuperer la liste des thematiques
betagouv/agora-back pull request #2
Opened 2023-04-04 11:32 UTC by imaneryane

première liste des thématiques

2023-04-04 12:07 UTC, thierrylee requested changes

2023-04-04 12:07 UTC, thierrylee commented on HELP.md
> +
A enlever ?

2023-04-04 12:07 UTC, thierrylee commented on Procfile
> +>>>>>>> 511e4afab475757ce21d3dcc5fe9ad3a3a0f2502
Il faut résoudre le conflit ici

2023-04-04 12:07 UTC, thierrylee commented on build.gradle.kts
> +	useJUnitPlatform()
J'ai l'impression qu'il y a un soucis avec tes tabulations

2023-04-04 13:28 UTC, imaneryane commented on build.gradle.kts
> +	useJUnitPlatform()
pas de tabulation de plus à mon niveau

2023-04-04 13:30 UTC, imaneryane commented on HELP.md
> +
Yes je l'ai enlever sur ma dernière PR

2023-04-06 08:18 UTC, thierrylee approved these changes

2023-04-06 08:18 UTC, merged