correction erreur + nommage du repository des notif + DTO et domain d…
betagouv/agora-back pull request #212
Opened 2023-09-11 13:35 UTC by imaneryane

…es notif

2023-09-12 14:52 UTC, thierrylee requested changes

2023-09-12 14:52 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qagModerating/QagModeratingController.kt
> -    private val sendNotificationQagModeratedUseCase: SendNotificationQagModeratedUseCase,
Bien vu 😮

2023-09-12 14:52 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/repository/NotificationCacheRepository.kt
> +        } ?: throw IllegalStateException("Notification cache has not been initialized")
Il va falloir qu'on gère ces cas, c'est arrivé y'a quelques temps

2023-09-12 15:57 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/repository/NotificationCacheRepository.kt
> +        } ?: throw IllegalStateException("Notification cache has not been initialized")
done

2023-09-13 07:24 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/notification/SendConsultationNotificationUseCase.kt
> +        for (userInfo in userRepository.getAllUsers())
Pour optimiser, tu peux stocker la liste des utilisateurs pour le stockage de la notif + l'envoi.

2023-09-13 07:24 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/notification/SendNotificationQagModeratedUseCase.kt
> +        val sendingNotificationResult = getQagAuthorFcmToken(qagId = qagId)?.let { fcmToken ->
Tu peux modifier `getQagAuthorFcmToken` pour que ça te renvoi le `userId` + `fcmToken`
ça permettrait d'éviter d'appeler une 2ème fois `getQagInfo` pour l'insert

2023-09-13 07:24 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/notification/SendNotificationQagModeratedUseCase.kt
> +                notificationRepository.insertNotification(
On avait pas dit qu'on ferai quand même l'insert même si la notification échoue ?

2023-09-13 07:24 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/notification/repository/NotificationRepository.kt
> +    fun getAllNotification(): List<Notification>
Avec un `s` du coup
Mais je me demande si tu en aura vraiment besoin... j'ai des doutes

2023-09-13 08:14 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/usecase/notification/SendConsultationNotificationUseCase.kt
> +        for (userInfo in userRepository.getAllUsers())
done

2023-09-13 08:32 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/usecase/notification/repository/NotificationRepository.kt
> +    fun getAllNotification(): List<Notification>
complètement raison! puisqu'on récupère la liste des notifications par userId. je l'enlève

2023-09-13 08:43 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/repository/NotificationRepositoryImpl.kt
> +                cacheRepository.initializeCache(allNotificationDTO + savedNotificationDTO)
Après réflexions, finalement il suffit de faire appel à `getAllNotificationDTO()`
Si on `save` la nouvelle notif avant de l'ajouter en cache, le `findAll` nous la renverra également. Plus besoin de l'ajouter avec ce `+ savedNotificationDTO` du coup

2023-09-13 08:50 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/repository/NotificationRepositoryImpl.kt
> +                cacheRepository.initializeCache(allNotificationDTO + savedNotificationDTO)
done

2023-09-13 14:22 UTC, thierrylee approved these changes

2023-09-13 14:22 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NotificationPaginatedController.kt
> +        } ?: ResponseEntity.status(HttpStatus.BAD_REQUEST).body(Unit)
Tu peux utiliser `ResponseEntity.badResult().body(Unit)` (2 occurences dans ce fichier)

2023-09-13 14:22 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NotificationPaginatedJson.kt
> +@JsonInclude(JsonInclude.Include.NON_NULL)
Pas besoin de cette annotation, rien n'est nullable dans cet objet JSON

2023-09-13 14:28 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NotificationPaginatedJson.kt
> +@JsonInclude(JsonInclude.Include.NON_NULL)
done

2023-09-13 14:31 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/notification/NotificationPaginatedController.kt
> +        } ?: ResponseEntity.status(HttpStatus.BAD_REQUEST).body(Unit)
done

2023-09-13 15:28 UTC, merged