feat/073-Liste-des-consultations-suivies
betagouv/agora-back pull request #57
Opened 2023-05-09 09:35 UTC by imaneryane

2023-05-09 14:32 UTC, thierrylee requested changes

2023-05-09 14:32 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/consultation/repository/ConsultationAnsweredCacheRepository.kt
> +
Est-ce qu'il faudrait pas ajouter une méthode pour `evict` le cache quand un utilisateur répond à une consultation du coup (et l'appeler) ?

2023-05-09 14:32 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/consultation/GetConsultationPreviewAnsweredListUseCase.kt
> +        return consultationPreviewAnsweredRepository.getConsultationAnsweredList(userId = userId)
Il faut transformer le `deviceId` en `userId` via le `LoginRepository`

2023-05-10 12:46 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/usecase/consultation/repository/ConsultationPreviewAnsweredRepository.kt
> +    fun getConsultationAnsweredList(userId: String): List<ConsultationPreviewAnsweredInfo>?
si le userId n'est pas un valid UUID, on retourne null

2023-05-10 13:44 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/usecase/consultation/repository/ConsultationPreviewAnsweredRepository.kt
> +    fun getConsultationAnsweredList(userId: String): List<ConsultationPreviewAnsweredInfo>?
done

2023-05-10 14:07 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/consultation/repository/ConsultationAnsweredCacheRepository.kt
> +
done

2023-05-10 16:09 UTC, merged