feat 88 qag recentes
betagouv/agora-back pull request #66
Opened 2023-05-11 14:26 UTC by imaneryane

2023-05-11 14:57 UTC, thierrylee requested changes

2023-05-11 14:57 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagInfoDatabaseRepository.kt
> +    fun getQagLatestList(): List<QagDTO>
Il faut exclure les QaGs qui ont des réponses

2023-05-11 14:57 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagInfoDatabaseRepository.kt
> +        value = "SELECT * FROM qags where thematique_id = :thematiqueId ORDER BY post_date DESC LIMIT 10",
Idem là

2023-05-11 14:57 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qagHome/QagHomeJsonMapper.kt
> +                ) },
Tu peux mutualiser la transformation domainQag -> QagLatestJson via une méthode privée

2023-05-11 16:12 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagInfoDatabaseRepository.kt
> +    fun getQagLatestList(): List<QagDTO>
done

2023-05-11 16:27 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qagHome/QagHomeJsonMapper.kt
> +                ) },
done

2023-05-12 07:09 UTC, thierrylee approved these changes

2023-05-12 07:14 UTC, merged