feat 88 qag suivies
betagouv/agora-back pull request #67
Opened 2023-05-12 14:32 UTC by imaneryane

2023-05-12 14:57 UTC, thierrylee requested changes

2023-05-12 14:57 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagCacheRepository.kt
> +    }
Pourquoi créer de nouvelles `sealed class` à chaque fois ? On pourrait réutiliser un `CacheListResult` non ?

2023-05-12 14:57 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagCacheRepository.kt
> +            qagPopularList ?: emptyList<QagDTO>(),
Oh mince j'avais pas vu, il faudra flusher le cache 🙄

2023-05-12 14:57 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagCacheRepository.kt
> +            thematiqueId?.toString() ?: QAG_LATEST_CACHE_KEY,
Autre chose que j'avais pas vu: s'il y a un filtre appliqué, il va écraser le cache des QaG populaires + récentes + suivies.
Il faut une clé unique pour chaque type de cache :
- populaire (sans et avec filtre)
- récentes (sans et avec filtre)
- suivies (sans et avec filtre)

2023-05-12 14:57 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedRepositoryImpl.kt
> +class QagSupportedRepositoryImpl(
Renommer en `QagSupportedListRepositoryImpl`

2023-05-12 15:00 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/qag/repository/QagSupportedListRepository.kt
> +    fun getQagSupportedList(thematiqueId: String?, userId: String?): List<QagInfo>
`userId` obligatoire donc non nullable

2023-05-15 11:31 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagCacheRepository.kt
> +    }
done

2023-05-15 11:34 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedRepositoryImpl.kt
> +class QagSupportedRepositoryImpl(
done

2023-05-15 11:36 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedRepositoryImpl.kt
> +            val thematiqueUUID = thematiqueId?.let(UUID::fromString)
done

2023-05-15 11:37 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedRepositoryImpl.kt
> +    override fun getQagSupportedList(thematiqueId: String?, userId: String?): List<QagInfo> {
done

2023-05-15 11:38 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedRepositoryImpl.kt
> +    private fun getQagSupportedListFromDatabase(thematiqueUUID: UUID?, userIdUUID: UUID): List<QagDTO> {
done

2023-05-15 11:45 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedRepositoryImpl.kt
> +            thematiqueUUID?.let { databaseRepository.getQagSupportedListWithThematique(thematiqueUUID, userIdUUID) }
done

2023-05-15 11:51 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/supportQag/repository/GetSupportQagRepositoryImpl.kt
> +    private fun getSupportQagFromDatabase(qagUUID: UUID, userIdUUID: UUID): SupportQagDTO? {
done

2023-05-15 11:52 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/supportQag/repository/GetSupportQagRepositoryImpl.kt
> +            val userIdUUID = UUID.fromString(userId)
done

2023-05-15 12:59 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagCacheRepository.kt
> +            thematiqueId?.toString() ?: QAG_LATEST_CACHE_KEY,
quand on ajoute ou on supprime un support QAG,je supprime les listes (avec et sans thématique) du cache

2023-05-15 13:22 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagCacheRepository.kt
> +                ?: userId.toString(),
Tu peux remplacer par :
`buildQagCacheKey(thematiqueId, userId.toString())`

Et il faudrait une méthode `buildQagCacheKey` qui resssemble à ça:
`return thematiqueId?.let { "$thematiqueId/$key" } ?: key`

2023-05-15 13:26 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedListRepositoryImpl.kt
> +            if (userUUID != null) {
Et du coup ici c'est forcément non null

2023-05-15 13:27 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedListRepositoryImpl.kt
> +                        userUUID
J'avais pas vu mais ça peut être intéressant des named arguments là

2023-05-15 13:28 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedListRepositoryImpl.kt
> +        cacheRepository.deleteQagSupportedList(UUID.fromString(thematiqueId), UUID.fromString(userId))
Houla, il faut try/catcher ça (et ajouter des tests si besoin)

2023-05-15 13:28 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedListRepositoryImpl.kt
> +        val qagDTO =
`qagDTOList` plutôt, vu qu'il y en a plusieurs

2023-05-15 13:30 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/supportQag/repository/SupportQagRepositoryImpl.kt
>          }
C'est très étrange comme façon de faire ... tu peux les stocker dans une variable et les traiter par la suite direct

2023-05-15 13:31 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/supportQag/DeleteSupportQagUseCase.kt
> +                thematiqueId = it.thematiqueId, userId = supportQagDeleting.userId
Pas besoin d'utiliser `validUserId` ici ? 🤔

2023-05-15 13:32 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/supportQag/InsertSupportQagUseCase.kt
> +                thematiqueId = it.thematiqueId, userId = supportQagInserting.userId
Même question ici

2023-05-15 13:44 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedListRepositoryImpl.kt
> +            if (userUUID != null) {
done

2023-05-15 13:46 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedListRepositoryImpl.kt
> +                        userUUID
done

2023-05-15 13:58 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedListRepositoryImpl.kt
> +        val qagDTO =
done

2023-05-15 14:00 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/supportQag/repository/GetSupportQagRepositoryImpl.kt
> +                CacheResult.CacheNotInitialized -> getSupportQagFromDatabase(qagUUID, userUUID)
done

2023-05-15 14:06 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/supportQag/repository/SupportQagRepositoryImpl.kt
>          }
je ne sais plus dans quelles circonstances j'ai écrit ce code :)

2023-05-15 14:06 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/supportQag/repository/SupportQagRepositoryImpl.kt
> +            supportQagCacheRepository.insertSupportQag(qagId, userId, null)
done

2023-05-15 14:29 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagCacheRepository.kt
> +                ?: userId.toString(),
done

2023-05-15 14:31 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagSupportedListRepositoryImpl.kt
> +        cacheRepository.deleteQagSupportedList(UUID.fromString(thematiqueId), UUID.fromString(userId))
done

2023-05-15 14:35 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/usecase/supportQag/DeleteSupportQagUseCase.kt
> +                thematiqueId = it.thematiqueId, userId = supportQagDeleting.userId
done

2023-05-15 14:35 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/usecase/supportQag/InsertSupportQagUseCase.kt
> +                thematiqueId = it.thematiqueId, userId = supportQagInserting.userId
done

2023-05-15 15:04 UTC, thierrylee approved these changes

2023-05-15 15:06 UTC, merged