first commit for PUT_moderate_qag
betagouv/agora-back pull request #86
Opened 2023-05-31 13:27 UTC by imaneryane

2023-05-31 14:28 UTC, thierrylee requested changes

2023-05-31 14:28 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/QagModeratingController.kt
> +    ): HttpEntity<*> {
`ResponseEntity`?

2023-05-31 14:28 UTC, thierrylee commented on src/test/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagModeratingRepositoryImplTest.kt
> +        @Test
Manque un saut de ligne et qu'est-ce qu'il se passe si on essai de mettre le status cible à : OPEN ou ARCHIVED ?

2023-05-31 14:44 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/QagModeratingController.kt
> +    ): HttpEntity<*> {
done. J'ai cru que pour responseEntity, il faut spécifier une classe Json pour le type de retour

2023-06-01 06:41 UTC, thierrylee commented on src/test/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagModeratingRepositoryImplTest.kt
> +        fun `putModeratingQagStatus - when database returns DTO and DTO status is OPEN and target status is archived - should return FAILURE`() {
Il manque toujours quelques sauts de lignes entre les différents tests.
Et je suis en train de me dire qu'on pourrait faire des tests paramétrés pour ce genre de cas

2023-06-01 06:42 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/QagModeratingController.kt
> +    fun putModeratingQagStatus(
Vu la sensibilité de cette API, il faut qu'on ajoute un `SecurityFilterChain` dans `WebSecurityConfig`

2023-06-01 08:10 UTC, imaneryane commented on src/test/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagModeratingRepositoryImplTest.kt
> +        fun `putModeratingQagStatus - when database returns DTO and DTO status is OPEN and target status is archived - should return FAILURE`() {
done

2023-06-02 08:45 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/QagModeratingController.kt
> +        val qagModeratingCount = getQagModeratingListUseCase.getModeratingQagCount()
Oh la bourde 🤦 
Bien vu

2023-06-02 09:04 UTC, thierrylee requested changes

2023-06-02 09:04 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagInfoRepositoryImpl.kt
> +            val targetStatusDTO = toDtoStatus(qagModeratingStatus)
Pas besoin de vérifier le `targetStatus` si qagDTO est null

2023-06-02 09:04 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagInfoRepositoryImpl.kt
> +            val qagDTO = getAllQagDTO().find { qagDTO -> qagDTO.id == qagUUID && qagDTO.status == STATUS_OPEN }
J'ai l'impression que y'a un peu de code mutualisable avec `getQagInfo`

2023-06-02 09:14 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagInfoCacheRepository.kt
> +    }
done

2023-06-02 09:22 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagInfoRepositoryImpl.kt
> +            val targetStatusDTO = toDtoStatus(qagModeratingStatus)
done

2023-06-02 09:25 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagInfoRepositoryImpl.kt
> +            val qagDTO = getAllQagDTO().find { qagDTO -> qagDTO.id == qagUUID && qagDTO.status == STATUS_OPEN }
le getQagInfo fait appel au mapper, dans notre cas on n'a pas besoin du mapper.

2023-06-02 09:29 UTC, thierrylee commented on src/test/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagInfoRepositoryImplTest.kt
> +            then(cacheRepository).should(times(1)).updateQag(updatedQagDTO = savedQagDTO)
Je viens seulement de voir, il manque un `then(cacheRepository).shouldHaveNoMoreInteractions()`
D'ailleurs en ajoutant ça le `times(1)` n'est plus nécessaire

2023-06-02 09:29 UTC, thierrylee commented on src/test/kotlin/fr/social/gouv/agora/infrastructure/qag/repository/QagInfoRepositoryImplTest.kt
> +            then(cacheRepository).should(times(1)).updateQag(updatedQagDTO = savedQagDTO)
Idem là

2023-06-02 09:50 UTC, thierrylee approved these changes

2023-06-02 09:50 UTC, thierrylee approved these changes

2023-06-02 09:52 UTC, merged