first commit for 144
betagouv/agora-back pull request #89
Opened 2023-06-02 13:52 UTC by imaneryane

2023-06-02 14:37 UTC, thierrylee requested changes

2023-06-02 14:37 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/login/SignupController.kt
> +        isSignUpEnabled = true //TODO suppress when featureFlags are configured in system
Du coup il faut que tu le configures :P

2023-06-02 14:37 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/login/SignupController.kt
> +            ResponseEntity.status(400).body(Unit)
J'ai découvert `ResponseEntity.status(HttpStatus.BAD_REQUEST)` pour faire moins "magic number" que ce 400

2023-06-02 14:37 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/login/SignupController.kt
> +            )?.let { userInfo ->
ça tient en 1 ligne non ?

2023-06-02 14:37 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/usecase/login/LoginUseCase.kt
> +    fun signUp(fcmToken: String): UserInfo? {
Maintenant ça ne peut plus être null du coup non ?

2023-06-02 14:37 UTC, thierrylee commented on src/main/resources/data.sql
>  ) ON CONFLICT DO NOTHING;
On peut complètement les enlever

2023-06-02 14:37 UTC, thierrylee commented on src/test/kotlin/fr/social/gouv/agora/usecase/login/LoginUseCaseTest.kt
> -    fun `signUp - when user with deviceId does not exists - should return result from generateUser`() {
Du coup on ne teste plus du tout `signUp` si tu enlève ce test

2023-06-02 15:19 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/login/SignupInfoJsonMapper.kt
>          )
Après discussions, il faut qu'on ajoute le `userId` dans le retour de signup

2023-06-05 08:01 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/login/SignupController.kt
> +        isSignUpEnabled = true //TODO suppress when featureFlags are configured in system
done sur mon .zshrc (export IS_SIGNUP_ENABLED='true')

2023-06-05 08:03 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/login/SignupController.kt
> +            ResponseEntity.status(400).body(Unit)
done

2023-06-05 08:07 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/usecase/login/LoginUseCase.kt
> +    fun signUp(fcmToken: String): UserInfo? {
done

2023-06-05 08:09 UTC, imaneryane commented on src/main/resources/data.sql
>  ) ON CONFLICT DO NOTHING;
done (suppression des 2 users)

2023-06-05 08:14 UTC, thierrylee commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/login/SignupController.kt
> +        isSignUpEnabled = true //TODO suppress when featureFlags are configured in system
il faut le faire aussi sur Scalingo ;)

2023-06-05 08:26 UTC, imaneryane commented on src/main/kotlin/fr/social/gouv/agora/infrastructure/login/SignupInfoJsonMapper.kt
>          )
done

2023-06-05 08:44 UTC, imaneryane commented on src/test/kotlin/fr/social/gouv/agora/usecase/login/LoginUseCaseTest.kt
> -    fun `signUp - when user with deviceId does not exists - should return result from generateUser`() {
yes plus de test signup

2023-06-05 09:13 UTC, thierrylee approved these changes

2023-06-05 09:18 UTC, merged